app: # like .env retreived in AppProperties           
  userId: 4e666efa-89e2-41bc-be83-21dc68478f96
  schoolId: 44d5d438-7afd-4595-be8e-294a08532138
  firebaseServiceAccount: ${FIREBASE_SERVICE_ACCOUNT:}


  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true





